import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import NavBar from "@/components/navBar";
import FooterMenu from "@/components/footerMenu";
import { Alegreya } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });
const alegreya = Alegreya({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "The Dev Space",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${alegreya.className} bg-light dark:bg-dark text-dark dark:text-light`}>
        {<NavBar session={session} />}
        <main className="max-w-screen-xl p-5 mx-auto">{children}</main>
        {<FooterMenu />}
      </body>
    </html>
  );
}
